// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemologinTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demologin() {
    // Test name: demo login
    // Step # | name | target | value
    // 1 | open | /login?logout | 
    driver.get("http://localhost:8888/login?logout");
    // 2 | setWindowSize | 550x691 | 
    driver.manage().window().setSize(new Dimension(550, 691));
    // 3 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 4 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 5 | type | name=username | ada_lovelace
    driver.findElement(By.name("username")).sendKeys("ada_lovelace");
    // 6 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 7 | type | name=password | supersecured
    driver.findElement(By.name("password")).sendKeys("supersecured");
    // 8 | click | css=.input-button | 
    driver.findElement(By.cssSelector(".input-button")).click();
    // 9 | click | css=.input-button | 
    driver.findElement(By.cssSelector(".input-button")).click();
    // 10 | click | linkText=Par ici pour en créer un | 
    driver.findElement(By.linkText("Par ici pour en créer un")).click();
    // 11 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 12 | type | css=input:nth-child(1) | gobin
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("gobin");
    // 13 | type | css=input:nth-child(2) | gobin
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("gobin");
    // 14 | type | css=input:nth-child(3) | gobin@mail.fr
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("gobin@mail.fr");
    // 15 | type | css=input:nth-child(4) | ahahah
    driver.findElement(By.cssSelector("input:nth-child(4)")).sendKeys("ahahah");
    // 16 | click | css=.input-button | 
    driver.findElement(By.cssSelector(".input-button")).click();
    // 17 | mouseOver | css=.input-button | 
    {
      WebElement element = driver.findElement(By.cssSelector(".input-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 18 | mouseOut | css=.input-button | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 19 | click | linkText=Connectez vous | 
    driver.findElement(By.linkText("Connectez vous")).click();
    // 20 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 21 | type | name=username | gobin
    driver.findElement(By.name("username")).sendKeys("gobin");
    // 22 | type | name=password | gobin
    driver.findElement(By.name("password")).sendKeys("gobin");
    // 23 | click | css=.input-button | 
    driver.findElement(By.cssSelector(".input-button")).click();
  }
}
